config/routes.rb
Rails.application.routes.draw do
  root "high_voltage/pages#show", id: "index"

  resources :users, only: [:new, :create, :destroy]
  get "user/edit", to: "users#edit", as: "edit_user"
  get "user", to: "users#show", as: "account"
  patch "user", to: "users#update", as: "update_user"
  delete "user", to: "users#destroy", as: "destroy_user"

  resources :sessions, only: [:new, :create, :destroy]

  get "register", to: "users#new", as: "register"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "where/:where/:value", to: "where#index", as: "where"

  get "legends", to: "legends#index"
  get "legends/:name", to: "legends#show", as: "legend_show"

  get "sort/:items/:sort_by", to: "sort#index", as: "sort"

  scope :api do
    get ":key/:type", to: "api#basic"
    get ":key/:type/:where/:value", to: "api#where"
    get ":key/:type/sort/:items/:sort_by", to: "api#sort"
    get ":key/:type/:category", to: "api#category"
  end

  resources :notifications, only: [:create, :update]
  get "show_notifications", to: "notifications#show", as: "show_notifications"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :claimed_profiles, -> { where checks_completed: 1 }
  has_many :event_signups
  has_many :memberships
  has_many :notifications
  has_many :rewards
  has_many :remember_tokens

  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z\d][a-z\d-]*[a-z\d]\z/i }
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action only: [:show] do
    redirect_to login_path unless current_user
  end

  before_action only: [:new] do
    redirect_to account_path if current_user
  end

  def show
    @user = current_user
    redirect_to root_path unless @user
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
    redirect_to root_path unless @user
  end

  def create
    generate_api_key

    @user = User.new(user_params)
    @user.api_key = @token

    if @user.save
      session[:user_id] = @user.id

      redirect_to account_path, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    params[:user].delete(:password).delete(:password_confirmation) if params[:user][:password].blank?
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    @claimed_profiles = ClaimedProfile.where(user_id: current_user.id)
    @claimed_profiles.destroy_all
    @event_signups = EventSignup.where(user_id: current_user.id)
    @event_signups.destroy_all
    @rewards = Reward.where(user_id: current_user.id)
    @rewards.destroy_all

    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def generate_api_key
    loop do
      @token = SecureRandom.base64.tr('+/=', 'Qrt')
      break @token unless User.exists?(api_key: @token)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_username_for_claimed_profile_uid(uid)
    profile = ClaimedProfile.find_by_profile_uid_and_checks_completed(uid, 1)

    if profile.present?
      return profile.username
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user, url: url do |f| %>
  <% if user.errors.any? %>
    <div class="form-alert">
      <div><strong><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</strong></div>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><small><%= message %></small></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= f.label :username, class: "form-label" %>
    <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
    <div class="form-hint">We recommend using a different username from the one you use in Apex Legends.</div>
  </div>

  <hr>

  <div class="form-field">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, placeholder: "Password", class: "form-control" %>

    <div class="form-hint">Please use a unique password that is different from the one you use for Apex Legends. Passwords are encrypted and securely stored.</div>
  </div>

  <div class="form-field">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation", class: "form-control" %>
  </div>

  <%= submit_tag "Submit", class: "button" %>
<% end %>

app/views/users/edit.html.erb
<% content_for :page_title, "Edit your account" %>

<div class="wrapper wrapper--tiny top-offset">
  <div class="item item--full-width">
    <h2 class="form-title">Editing your account</h2>

    <%= render "form", user: @user, url: update_user_path %>

    <div class="form-danger-zone">
      Danger zone!

      <%= link_to "Delete your account", destroy_user_path, method: :delete, data: { confirm: "Are you sure you wish to delete your account? This cannot be undone." } %>

      <div class="form-hint">
        Deleting your account is a permanent action and cannot be undone. Your account will be completely wiped from our database, along with any associations to it.
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :page_title, "Create an account" %>

<div class="wrapper wrapper--tiny top-offset">
  <div class="item item--full-width">
    <h2 class="form-title">Create an account</h2>

    <%= render "form", user: @user, url: users_path %>
  </div>

  <center><small>Already have an account? <%= link_to "Log in", login_path %></small></center>
</div>

app/views/users/show.html.erb
<% content_for :page_title, "Your account" %>

<div class="wrapper wrapper--tiny top-offset">
  <div class="item item--full-width">
    <div class="notice"><%= notice %></div>

    <div>Logged in as <strong><%= current_user.username %></strong></div>

    <hr>
      <small>Your API Key: <strong><%= current_user.api_key %></strong></small>
    <hr>

    <%= link_to "Edit your account", edit_user_path %>
    <%= link_to "Logout", logout_path %>
  </div>
</div>