config/routes.rb
Rails.application.routes.draw do
  root "high_voltage/pages#show", id: "index"

  resources :users, only: [:new, :create, :destroy]
  get "user/edit", to: "users#edit", as: "edit_user"
  get "user", to: "users#show", as: "account"
  patch "user", to: "users#update", as: "update_user"
  delete "user", to: "users#destroy", as: "destroy_user"

  resources :sessions, only: [:new, :create, :destroy]

  get "register", to: "users#new", as: "register"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "where/:where/:value", to: "where#index", as: "where"

  get "legends", to: "legends#index"
  get "legends/:name", to: "legends#show", as: "legend_show"

  get "sort/:items/:sort_by", to: "sort#index", as: "sort"

  scope :api do
    get ":key/:type", to: "api#basic"
    get ":key/:type/:where/:value", to: "api#where"
    get ":key/:type/sort/:items/:sort_by", to: "api#sort"
    get ":key/:type/:category", to: "api#category"
  end

  resources :notifications, only: [:create, :update]
  get "show_notifications", to: "notifications#show", as: "show_notifications"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :login_from_cookie

  def login_from_cookie
    return unless cookies.encrypted[:remember_token] && !current_user
    token = RememberToken.find_by_token(cookies.encrypted[:remember_token])

    if token
      user = token.user

      if user
        session[:user_id] = user.id
      end
    end
  end

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  helper_method :membership

  def membership
    if current_user
      current_user.memberships.where("created_at > ?", 1.month.ago).last
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_exists?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end

  def to_slug(string)
    string.downcase.gsub(" ", "-")
  end
end

app/views/application/_ad.html.erb
<div class="ad-container">
  <style>
    .mobile-ad { display: inline-block }
    .desktop-ad { display: none }
    @media (min-width: 800px) { .mobile-ad { display: none } }
    @media (min-width: 800px) { .desktop-ad { display: inline-block } }
  </style>
  <ins class="adsbygoogle desktop-ad"
    style="width:728px;height:90px"
    data-ad-client="ca-pub-6800703662222824"
    data-ad-slot="4860907572"></ins>
  <ins class="adsbygoogle mobile-ad"
    style="width:320px;height:100px"
    data-ad-client="ca-pub-6800703662222824"
    data-ad-slot="1005423044"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>

  <span class="ad-container__title">Advertisement</span>
  <div class="ad-container__background"></div>
</div>

app/views/application/_analytics_code.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-46852314-9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag("js", new Date());

  gtag("config", "UA-46852314-9", { "anonymize_ip": true });
</script>

app/views/application/_footer.html.erb
<footer class="footer">
  <p>
    Copyright &copy; 2019 | All images and icons belong to their respective owner.
  </p>

  <p class="text-right">
    Contribute on <%= link_to "GitHub", "https://github.com/Mitcheljager/apexdata", target: "_blank" %>
  </p>
</footer>

app/views/application/_header.html.erb
<header class="header">
  <div class="header__top">
    <div class="wrapper">
      <h1 class="header__logo-top">
        <%= link_to raw("ApexData.<strong>gg</strong>"), root_path %>
        &nbsp;|&nbsp; Apex Legends Data and Stats
      </h1>
    </div>
  </div>

  <div class="header__bottom">
    <div class="wrapper">
      <div class="header__content">
        <div class="navigation-open">
          <%= inline_svg("layout/menu.svg") %>
        </div>
        <%= render "navigation" %>
      </div>

      <div class="header__logo">
        <%= link_to image_tag("layout/apexlogo.png", alt: "Apex Legends logo"), root_path, class: "logo__image" %>
      </div>
    </div>
  </div>
</header>

app/views/application/_item.html.erb
<article class="item <%= "item--compact" if compact? %> <%= "item--more-data" if alldata? %>" data-compare-item="<%= item["name"].downcase.gsub(" ", "_") %>">
  <div class="item__content">
    <%= link_to "#", class: "button button--small item__top-action", data: { action: "compare" }, title: "Compare other items against this. Hover over values to see the difference between the two." do %>
      Compare
    <% end %>

    <div class="item__description">
      <div class="item__title heading heading--small">
        <h3 class="heading__title">
          <%= link_to item["name"], where_path("name", item["name"].downcase.dasherize.gsub(" ", "-")) if item["name"] %>
        </h3>
        <div class="heading__line"></div>
      </div>

      <div class="item__data-wrapper">
        <div class="item__main">
          <div class="columns">
            <%= tag.div class: "columns__column item__large-info" do %>
              <span>Damage</span>
              <div data-compare-target="damage"><%= item["damage"] %></div>
              <%= content_tag :small, "x#{item["damage_modifier"]}" if item["damage_modifier"] %>
            <% end if item["damage"] %>

            <%= tag.div class: "columns__column item__large-info" do %>
              <span>RPM</span>
              <div data-compare-target="rate-of-fire"><%= item["rate_of_fire"] %></div>
            <% end if item["rate_of_fire"] %>
          </div>

          <%= tag.div class: "item__small-info" do %>
            Damage per second <span><div data-compare-target="dps"><%= item["damage_per_second"] %></div></span>
          <% end if item["damage_per_second"] %>

          <%= tag.div class: "item__small-info" do %>
            Headshot damage <span><div data-compare-target="headshot-damage"  data-modify-target="headshot_damage_modifier"><%= item["headshot_damage"] %></div></span>
          <% end if item["headshot_damage"] %>

          <div class="item__tray">
            <div class="item__ammo-type">
              <%= link_to image_tag("ammo_types/#{ item["ammo_type"] }.png", alt: item["ammo_type"].humanize + " ammo", title: item["ammo_type"].humanize + " ammo"), where_path("ammo-type", item["ammo_type"].dasherize), class: "item__icon" if item["ammo_type"] %>

              <%= tag.div do %>
                <%= image_tag "fire_mode/single.png", class: "item__fire-mode", alt: "Single Fire", title: "Single Fire" if item["fire_modes"]["single"] %>
                <%= image_tag "fire_mode/auto.png", class: "item__fire-mode", alt: "Automatic Fire", title: "Automatic Fire" if item["fire_modes"]["auto"] %>
                <%= image_tag "fire_mode/burst.png", class: "item__fire-mode", alt: "Burst Fire)", title: "Burst Fire ( #{item["fire_modes"]["burst"] } Shots )" if item["fire_modes"]["burst"] %>
              <% end if item["fire_modes"] %>
            </div>

            <% if alldata? %>
              <%= link_to "Less data", "#", class: "button", data: { action: "item-more-data" } %>
            <% else %>
              <%= link_to "More data", "#", class: "button button--primary", data: { action: "item-more-data" } %>
            <% end %>
          </div>
        </div>

        <div class="item__extra columns">
          <div class="columns__column">
            <%= tag.div class: "item__small-info" do %>
              Legshot damage <span><div data-compare-target="legshot_damage"><%= item["legshot_damage"] %></div></span>
            <% end if item["legshot_damage"] %>

            <%= tag.div class: "item__small-info" do %>
              Ammo capacity <span><div data-compare-target="ammo_capacity" data-modify-target="ammo_increase" data-modify-round><%= item["ammo_capacity"] %></div></span>
            <% end if item["ammo_capacity"] %>

            <%= tag.div class: "item__small-info" do %>
              Damage per magazine
              <span>
                <div data-compare-target="damage_per_magazine" data-modify-target="ammo_increase" data-modify-round>
                  <%= item["damage_per_magazine"] %>
                </div>
              </span>
            <% end if item["damage_per_magazine"] %>

            <%= tag.div class: "item__small-info" do %>
              Projectile speed <span><div data-compare-target="projectile_speed"><%= item["projectile_speed"] / 10 %></div></span> <small>m/s</small>
            <% end if item["projectile_speed"] %>

            <hr>

            <%= tag.div class: "item__small-info" do %>
              Tactical reload
              <span>
                <div data-compare-target="tactical_reload" data-compare-inverse="true" data-modify-target="reload_time"><%= item["tactical_reload"] %></div>
              </span>
              <small>s</small>
            <% end if item["tactical_reload"] %>

            <%= tag.div class: "item__small-info" do %>
              Empty reload <span><div data-compare-target="empty_reload" data-compare-inverse="true" data-modify-target="reload_time"><%= item["empty_reload"] %></div></span> <small>s</small>
            <% end if item["empty_reload"] %>

            <%= tag.div class: "item__small-info" do %>
              Draw time <span><div data-compare-target="draw_time" data-compare-inverse="true" data-modify-target="draw_time"><%= item["draw_time"] %></div></span> <small>s</small>
            <% end if item["draw_time"] %>

            <%= tag.div class: "item__small-info" do %>
              Holster time <span><div data-compare-target="holster_time" data-compare-inverse="true" data-modify-target="holster_time"><%= item["holster_time"] %></div></span> <small>s</small>
            <% end if item["holster_time"] %>
          </div>

          <%= tag.div class:"columns__column" do %>
            <strong>Attachments</strong> <small><%= link_to "View all", page_path("attachments") %></small>

            <% if item["available_attachments"] %>
              <%= render "pages/attachments_table", item: item %>

              <small class="tiny-help">Click on the icons to see how the values would change by adding the attachment. These values are rough estimates and are a work in progress.</small>
            <% else %>
              <div>
                <small>None</small>
              </div>
            <% end %>
          <% end %>

          <%= tag.div class: "columns__column columns__column--half" do %>
            <strong title="Spray pattern. Red indicates the first shot. Add a Barrel Stabilizer to see how it affects the spray.">Spray</strong>

            <%= render "pages/spray_pattern", spray: item["spray_pattern"] %>
          <% end if item["spray_pattern"]%>
        </div>
      </div>
    </div>

    <% unless compact? %>
      <% image_path = asset_exist?("weapons/#{ item["name"].downcase.gsub(" ", "_") }.jpg") ? "#{ item["name"].downcase.gsub(" ", "_") }" : "placeholder" %>

      <div class="item__image-wrapper">
        <picture>
          <source srcset="<%= image_url "weapons/webp/#{ image_path }.webp" %>" type="image/webp">
          <source srcset="<%= image_url "weapons/#{ image_path }.jpg" %>" type="image/jpeg">
          <%= image_tag "weapons/#{ image_path }.jpg", class: "item__image", alt: item["name"].humanize %>
        </picture>
      </div>
    <% end %>
  </div>
</article>

app/views/application/_navigation.html.erb
<nav class="navigation">
  <div class="navigation-close">
    <%= inline_svg("layout/close.svg") %>
  </div>

  <div class="dropdown">
    <%= link_to page_path("weapons"), class: current_page?(page_path("weapons")) ? "active" : "" do %>
      Weapons & items
      <%= inline_svg("layout/icon-dropdown.svg") %>
    <% end %>

    <div class="dropdown__content">
      <div class="dropdown__inner">
        <%= link_to "All", page_path("weapons"), class: current_page?(page_path("weapons")) ? "active" : "" %>
        <%= link_to "SMGs", page_path("sub-machine-guns"), class: current_page?(page_path("sub-machine-guns")) ? "active" : "" %>
        <%= link_to "Assault Rifles", page_path("assault-rifles"), class: current_page?(page_path("assault-rifles")) ? "active" : "" %>
        <%= link_to "LMGs", page_path("light-machine-guns"), class: current_page?(page_path("light-machine-guns")) ? "active" : "" %>
        <%= link_to "Pistols", page_path("pistols"), class: current_page?(page_path("pistols")) ? "active" : "" %>
        <%= link_to "Shotguns", page_path("shotguns"), class: current_page?(page_path("shotguns")) ? "active" : "" %>
        <%= link_to "Sniper Rifles", page_path("sniper-rifles"), class: current_page?(page_path("sniper-rifles")) ? "active" : "" %>

        <hr>

        <%= link_to "Grenades", page_path("grenades"), class: current_page?(page_path("grenades")) ? "active" : "" %>
        <%= link_to "Consumables", page_path("consumables"), class: current_page?(page_path("consumables")) ? "active" : "" %>
        <%= link_to "Equipment", page_path("equipment"), class: current_page?(page_path("equipment")) ? "active" : "" %>
        <%= link_to "Attachments", page_path("attachments"), class: current_page?(page_path("attachments")) ? "active" : "" %>
      </div>
    </div>
  </div>

  <div class="dropdown">
    <%= link_to legends_path, class: current_page?(legends_path) ? "active" : "" do %>
      Legends
      <%= inline_svg("layout/icon-dropdown.svg") %>
    <% end %>

    <div class="dropdown__content">
      <div class="dropdown__inner">
        <%= link_to "All", legends_path, class: current_page?(legends_path) ? "active" : "" %>
        <% legends_list.each do |legend| %>
          <%= link_to legend, legend_show_path(legend.downcase), class: current_page?(legend_show_path(legend.downcase)) ? "active" : "" %>
        <% end %>
      </div>
    </div>
  </div>

  <%= link_to "API", page_path("api"), class: current_page?(page_path("api")) ? "active" : "" %>
</nav>